import enum


class NotificationTypes(enum.Enum):
    INITIAL_INFO = 1
    STATE_NARATOR_CHOOSING_CARD = 2
    NARATOR_CHOOSE_CARD = 3
    STATE_CHOOSING_CARD = 4
    PLAYER_CHOOSE_CARD = 5
    STATE_GUESSING_CARD = 6
    PLAYER_GUESS_CARD = 7
    STATE_SHOWING_RESULTS = 8
    PLAYER_APPROVE_RESULTS = 9
    STATE_SHOWING_LEADERBOARD = 10
    PLAYER_APPROVE_LEADERBOARD = 11
